package com.bookkaro.assistant.core

/**
 * P40 test helper — app/src/test/resources/p40-handoff-vectors.json, generated by scripts/p40-android-vectors.ts from
 * the REAL backend handoff code (signed snapshot of a mock session) + the extension's JS guard results. Test data only.
 */
@Suppress("UNCHECKED_CAST")
object Vectors {
    val root: Map<String, Any?> by lazy {
        val text = Vectors::class.java.classLoader!!.getResourceAsStream("p40-handoff-vectors.json")!!.bufferedReader(Charsets.UTF_8).use { it.readText() }
        Json.parse(text) as Map<String, Any?>
    }
    val cases: List<Map<String, Any?>> get() = root["cases"] as List<Map<String, Any?>>
    fun case(name: String): Map<String, Any?> = cases.first { it["name"] == name }
    fun snapshot(name: String): Map<String, Any?> = case(name)["snapshot"] as Map<String, Any?>
    fun key(name: String = "valid"): String = case(name)["key"] as String
    fun now(name: String = "valid"): Long = (case(name)["now"] as Number).toLong()
    fun expected(name: String = "valid"): HandoffGuard.Expected {
        val e = case(name)["expected"] as Map<String, Any?>
        return HandoffGuard.Expected(e["handoffId"] as String, (e["reviewVersion"] as Number).toLong())
    }
}
